### ISSUE TITLE
Crash on iOS 12.5.4 and Ti SDK 10.0.0.GA

### ISSUE THREAD

**Issue by Max87ZA** [viezel/NappDrawer#231]
Hi guys, I have a problem with this module since I upgraded to Ti SDK 10. On iOS 12.5.4(tested with iP6) it crashes right after startup. I found logs via xcode:
`erminating app due to uncaught exception ‘UIViewControllerHierarchyInconsistency’, reason: ‘child view controller:<UINavigationController: 0x103037600> should have parent view controller:<TiViewController: 0x1020911a0> but actual parent is:<TiRootViewController: 0x10282de00>’`

Building app with 9.3.2.GA works fine. Tested with newest 2.1.1 version of the module... Please can it be fixed? Thanks

**Comment by mbender74** [comment]
https://github.com/mbender74/NappDrawer

I fixed that error!

**Comment by jquick-axway** [comment]
@mbender74 , I'm hearing that this is still an issue when you put a `NavigationWindow` within a `NappDrawer`. It sounds like the `NappDrawer` code needs to change grab the next view controller up in the hierarchy kind of like how it's handled below. What do you think?
https://github.com/appcelerator/titanium_mobile/pull/12930/files

**Comment by mbender74** [comment]
works great with NavigationWindow!
Sure, you need to use 10.0.1.GA or 10.1.0 (master).....
Using NavigationWindows as centerWindow no problem...

**Comment by ewanharris** [comment]
@mbender74, I submitted a PR to fix the specific case Josh was referring to https://github.com/mbender74/NappDrawer/pull/1
